apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cbs-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Priyanka-jborse/k8s.git'
    targetRevision: HEAD
    path: cbs-microservice/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

