apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cbs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Priyanka-jborse/k8s.git'
    targetRevision: main
    path: Micro/CBS_CLZ_COM/argocd/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

